# sway  (~/.config/sway/config)
bindsym Ctrl+Alt+b exec ~/.local/bin/brevity
bindsym Ctrl+Alt+Shift+b exec ~/.local/bin/brevity --restore

# hyprland  (~/.config/hypr/hyprland.conf)
bind = CTRL ALT, B, exec, ~/.local/bin/brevity
bind = CTRL ALT SHIFT, B, exec, ~/.local/bin/brevity --restore

# i3  (~/.config/i3/config)
bindsym Ctrl+Mod1+b exec --no-startup-id ~/.local/bin/brevity
